[start_tftpd]
command:/usr/local/etc/rc.d/netboot_tftpd start
parameters:
type:script
message:starting netboot tftpd

[stop_tftpd]
command:/usr/local/etc/rc.d/netboot_tftpd stop
parameters:
type:script
message:stopping netboot tftpd

[restart_tftpd]
command:/usr/local/etc/rc.d/netboot_tftpd restart
parameters:
type:script
message:restarting netboot tftpd

[status_tftpd]
command:/usr/local/etc/rc.d/netboot_tftpd status; exit 0
parameters:
type:script_output
message:request netboot tftpd status

[start_http]
command:/usr/local/etc/rc.d/netboot_http start
parameters:
type:script
message:starting netboot http

[stop_http]
command:/usr/local/etc/rc.d/netboot_http stop
parameters:
type:script
message:stopping netboot http

[restart_http]
command:/usr/local/etc/rc.d/netboot_http restart
parameters:
type:script
message:restarting netboot http

[status_http]
command:/usr/local/etc/rc.d/netboot_http status; exit 0
parameters:
type:script_output
message:request netboot http status

[start_sftp]
command:/usr/local/etc/rc.d/netboot_sftp start
parameters:
type:script
message:starting netboot sftp

[stop_sftp]
command:/usr/local/etc/rc.d/netboot_sftp stop
parameters:
type:script
message:stopping netboot sftp

[restart_sftp]
command:/usr/local/etc/rc.d/netboot_sftp restart
parameters:
type:script
message:restarting netboot sftp

[status_sftp]
command:/usr/local/etc/rc.d/netboot_sftp status; exit 0
parameters:
type:script_output
message:request netboot sftp status

[reload]
command:configctl template reload OPNsense/Netboot
parameters:
type:script
message:reloading netboot configuration

[fetch_url]
command:/usr/local/opnsense/scripts/netboot/fetch_url.sh %s %s
parameters:%s %s
type:script_output
message:fetching url to netboot content root

[bootstrap_netboot_xyz]
command:/usr/local/opnsense/scripts/netboot/bootstrap_netboot_xyz.sh
parameters:
type:script_output
message:fetching both netboot.xyz BIOS and UEFI iPXE binaries
